load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "image_helper",
    srcs = ["image_helper.cc"],
    hdrs = ["image_helper.h"],
    deps = [
        "//src/includes/object_detection:common_dependencies",
    ],
)
